version: "3.7"

services:
  support_db:
    container_name: support_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=support_db
    image: postgres:15.3-alpine
